In [3]:
import numpy as np

#1
3 * np.array([2,5,0,6,8,10,6,7,5,7])*2*np.array([8,6,7,9,6,6,2,3,2,3]),\
6 * np.array([9,6,7,7,0,1,6,8,1,2])*5*np.array([0,2,2,6,7,8,8,3,1,8]),\
np.array([2,5,0,6,8,10,6,7,5,7])*np.array([8,6,7,9,6,6,2,3,2,3]),\
np.array([9,6,7,7,0,1,6,8,1,2])*np.array([0,2,2,6,7,8,8,3,1,8])


(array([ 96, 180,   0, 324, 288, 360,  72, 126,  60, 126]),
 array([   0,  360,  420, 1260,    0,  240, 1440,  720,   30,  480]),
 array([16, 30,  0, 54, 48, 60, 12, 21, 10, 21]),
 array([ 0, 12, 14, 42,  0,  8, 48, 24,  1, 16]))

In [4]:
def transpose(A):
    A_tr = np.zeros((A.shape[1], A.shape[0]))
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            A_tr[j][i] = A[i][j]
    return A_tr

transpose(np.array([[2,1,7,4],[5,6,7,3],[9,8,2,12],[11,14,15,15]]))

array([[ 2.,  5.,  9., 11.],
       [ 1.,  6.,  8., 14.],
       [ 7.,  7.,  2., 15.],
       [ 4.,  3., 12., 15.]])

In [5]:
transpose(np.array([[3,7,8,3,6],[2,5,9,4,13]]))

array([[ 3.,  2.],
       [ 7.,  5.],
       [ 8.,  9.],
       [ 3.,  4.],
       [ 6., 13.]])

In [14]:
from sympy import *

a1, a2 = symbols('a1, a2')

MSE = 1 / 4 * ((4.1 * a1 + 3.9 * a2 - 4.0)**2 + \
               (4.7 * a1 + 4.2 * a2 - 4.3)**2 + \
               (3.1 * a1 + 2.9 * a2 - 3.0)**2 + \
               (4.9 * a1 + 5.0 * a2 - 4.9)**2)

MSEa1 = diff(MSE, a1)
MSEa2 = diff(MSE, a2)

step = 0.01
loss = 100
point = np.array([0, 0])
i = 0
while loss > 6.36:    
    grad = np.array([MSEa1.subs({a1: point[0], a2: point[1]}), 
                     MSEa2.subs({a1: point[0], a2: point[1]})])
    point = point - step*grad
    loss = MSE.subs({a1: point[0], a2: point[1]})
    i += 1
print("Потребовалось %d шагов" % i, ", точка (%f, %f)" % (point[0], point[1]), "mse = %f" % loss)      

#Что-то явно не так

Потребовалось 1 шагов , точка (0.349600, 0.334300) mse = 1.589348
