In [ ]:
#Тест параметрические критерии
#Вопрос 1 - Статистика Лагранжа

In [ ]:
#Вопрос 2 - Вариант, где используются несовпадения между двумя выборками + размер выборок n

In [36]:
import math
#Вопрос 3 - H0 зевота незаразительна, отклонения случайны (p1=p2), H1 - зевота заразительна
#Зевание/Выборка    I    II
#Зевает            10    4
#Не зевает         24    12
#n                 34    16
p1 = 10/34
p2 = 4/16
n1 = 34
n2 = 16
P = (p1*n1 + p2*n2)/(n1 + n2)
#Z-критерий
z = (p1-p2)/math.sqrt(P*(1-P)*(1/n1 + 1/n2))

from scipy.stats import norm
            
z, 1-norm.cdf(z)
#Таким образом, разница татистически незначима ввиду высокого уровня значимости

(0.32410186177608225, 0.37293045872523534)

In [20]:
#Вопрос 4
#H0 - вероятности одинаковы
#H1 - вероятности отличаются
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

df = pd.read_csv("banknotes.txt", delimiter='\t')

df.head()

train, test = train_test_split(df, test_size=50, train_size=150, random_state=1)

X1 = train[["X1", "X2", "X3"]]
X2 = train[["X4", "X5", "X6"]]
y = train[["real"]]


classifier1 = LogisticRegression().fit(X1, y)
classifier2 = LogisticRegression().fit(X2, y)

answer1 = classifier1.predict(test[["X1", "X2", "X3"]])
answer2 = classifier2.predict(test[["X4", "X5", "X6"]])

real = np.array(test["real"].tolist())

diff1 = np.abs(real-answer1)
diff2 = np.abs(real-answer2)
diff3 = diff1 - diff2
real, answer1, answer2, diff1, diff2, diff3

C:\bin\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\bin\anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\bin\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\bin\anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


(array([1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
        1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
        1, 1, 0, 1, 0, 0]),
 array([1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
        1, 0, 1, 0, 0, 0], dtype=int64),
 array([1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
        1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
        1, 1, 0, 1, 0, 0], dtype=int64),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
        0, 1, 1, 1, 0, 0], dtype=int64),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0], dtype=int64),
 array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0, -1, 

In [30]:
import math
#как видно из разниц ответов, классификатор 2 предсказывает значительно точнее на тестовой выборке
#из diff3 посчитаем необходимые параметры для формулы Z-критерия для двух связанных выборок
#f - когда X1 == 1, а X2 == 0, в нашем случае это количество единиц
#g - когда X2 == 1, а X1 == 0, в нашем случае это количество минус единиц
f = 10
g = 1
n = 50
z = (f-g)/math.sqrt(f+g-((f-g)**2)/n)

z

2.9386041680175268

In [31]:
#Полученное значение критерия Z укладывается в nhb сигмы распределения N(0,1)
#Посчитаем значимость для разницы долей, H1 - что различны!

2*(1-norm.cdf(z))
#Цифра 3

0.0032969384555543435

In [35]:
z_i = norm.ppf(0.975)
i1 = (f-g)/n - z_i*math.sqrt((f+g)/(n**2) - ((f-g)**2)/(n**3)) #формула из лекций про доверительные интервалы
(f-g)/n, i1
#нужно 

(0.18, 0.059945206279614305)